### ISSUE TITLE
(if model has a space in the name) Exception loading config: [Errno 2] No such file or directory: 'models\\dreambooth\\db_config.json'

### ISSUE THREAD

**Issue by morphinapg** [d8ahazard/sd_dreambooth_extension#1129]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
Dreambooth revision: 3324b6ab7fa661cf7d6b5ef186227dc5e8ad1878
Successfully installed accelerate-0.17.1 fastapi-0.90.1 gitpython-3.1.31 requests-2.28.2 starlette-0.23.1 tensorboard-data-server-0.7.0 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17.dev476 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.17.1 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

If I create a model with a space in the name, I get this error when either trying to use the performance wizard, or trying to load saved settings. If I create a model without any spaces in the name, then I can do both just fine. For now I can obviously just avoid using spaces in my model names, but this wasn't an issue in older versions.

For the example below, in dreambooth I created a model called "test model" which gave me the error. If I just call it "test" it worked just fine.

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
Model dir set to: models\dreambooth\test  model
Loading model from checkpoint.
Loading ckpt...
Pred and size are epsilon and 512, using config: C:\Stable Diffusion\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-default.yaml
v1 model loaded.
Trying to load: C:\Stable Diffusion\models\Stable-diffusion\v1-5-pruned.yaml
Converting unet...
Converting vae...
Converting text encoder...
Saving text_encoder
Saving tokenizer
Checkpoint successfully extracted to models\dreambooth\test  model\working
Restored system models.
Duration: 00:00:27
Exception loading config: [Errno 2] No such file or directory: 'models\\dreambooth\\db_config.json'
Traceback (most recent call last):
  File "C:\Stable Diffusion\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 386, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\dreambooth\\db_config.json'
Can't load config!
Traceback (most recent call last):
  File "C:\Stable Diffusion\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 1003, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "C:\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 400, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "C:\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 285, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: HTML.update() got an unexpected keyword argument 'choices'
Exception loading config: [Errno 2] No such file or directory: 'models\\dreambooth\\db_config.json'
Traceback (most recent call last):
  File "C:\Stable Diffusion\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 386, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\dreambooth\\db_config.json'
Traceback (most recent call last):
  File "C:\Stable Diffusion\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Stable Diffusion\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Stable Diffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Stable Diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Stable Diffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Stable Diffusion\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 190, in performance_wizard
    save_samples_every = gr_update(config.save_preview_every)
AttributeError: 'NoneType' object has no attribute 'save_preview_every'
```

### 4. Environment

What OS? WIndows 11

If Windows - WSL or native? native

What GPU are you using? RTX 3080Ti (12 GB)

**Comment by TheBudderBomb** [comment]
This exact same thing was happening to me as well, but even with names that contained dashes or underscores in lieu of spaces.

**Comment by morphinapg** [comment]
> This exact same thing was happening to me as well, but even with names that contained dashes or underscores in lieu of spaces.

Can confirm

**Comment by KC2021** [comment]
In the latest version it's running the same code twice at from_file() in db_config.py asynchronously based on putting in some print statements in order. I find this issue easy to duplicate when selecting or creating a model in the Dreambooth extension, the same behaviour occurs when spaces or not exist at all in the path/model. Sometimes it creates the model but then populates the fields with Error. Sounds like thread safety issues. I am on Windows 10, cannot confirm if it occurs on Linux.

The sanitize_name() function runs fine for literal strings and works fine in isolation with runtime strings. But model_name becomes empty when the string is input into it from the runtime so the santising function itself isn't the problem but rather the input.

Looks to be a environment thread/cache issue, possibly in part due to it running twice. I am not sure why as model_name isn't overwritten by reference, but has it's reference changed at 'model_name = sanitize_name(model_name)'.

Related to https://github.com/d8ahazard/sd_dreambooth_extension/issues/858

**Comment by ArrowM** [comment]
Please `git checkout dev` and see if cb1ba379c460a888f243f457bf51e3b4698ae35e resolves your issue.

**Comment by Kiomarou** [comment]
I personally got it working. Poor type assertions as typical of Python as it is too implicit for data science like this, no idea why data scientists use it. That thread issue needs resolving, though.

**Comment by morphinapg** [comment]
> Please `git checkout dev` and see if [cb1ba37](https://github.com/d8ahazard/sd_dreambooth_extension/commit/cb1ba379c460a888f243f457bf51e3b4698ae35e) resolves your issue.

It does seem to solve the issue thanks
