### ISSUE TITLE
Four duplicate items in requirements.txt

### ISSUE THREAD

**Issue by ReflectionRip** [d8ahazard/sd_dreambooth_extension#128]
**Have you read the Readme?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 3a452da3cd9953007b681b24d054a5450e612083
Diffusers version is  0.7.2
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**
There are 4 duplicate items in requirements.txt
pillow
gradio
basicsr
accelerate

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**
What OS?
Windows 10
If Windows - WSL or native?
WSL
What GPU are you using?
RTX 3060

**Comment by Giganoob23** [comment]
Yeah there is something most definitely wrong with installing/updating this since latest commits. Opened stable diffusion today after a few days, saw dreambooth was out of date, tried to update, got this:

Reloading extensions
Reloading custom scripts
Reloading modules: modules.ui
Refreshing Model List
Restarting Gradio
Error executing callback ui_tabs_callback for C:\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py
Traceback (most recent call last):
  File "C:\StableDif\stable-diffusion-webui\modules\script_callbacks.py", line 93, in ui_tabs_callback
    res += c.callback() or []
  File "C:\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 123, in on_ui_tabs
    fn=conversion.compile_checkpoint,
AttributeError: module 'dreambooth.conversion' has no attribute 'compile_checkpoint'

Might be an issue on automatik's UI I thought. Tried restarting the UI. Got stuck on "installing requirements for web UI" for several minutes with no progress. Tried deleting the dreambooth extension entirely and re-installing from automatik's webUI. When restarting the web-ui and it began checking requirements for dreambooth, again, 10 mins of waiting "checking torch and torch vision versions". Doesn't seem normal.

**Comment by d8ahazard** [comment]
So, the problem is that automatic is trying to install one set of requirements, I'm trying to install another. 

The solution?

Copy the contents of one of these example scripts, add your own commandline args back in, and then try running.

This will override the CUDA and requirements files with just mine, solving these issues.

https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/webui-user-dreambooth.bat
https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/webui-user-dreambooth.sh

**Comment by Giganoob23** [comment]
> 

Don't think overwriting the original requirements of the webui with dreambooth requirements is wise. It might be an ok bandaid fix for now but what guarantees it won't break another feature of the automatik web-ui in the near future when automatik updates the requirements further and they're ignored while we're launching web-ui because we're pointing to dreambooth requirements instead of automatik requirements?

**Comment by d8ahazard** [comment]
> Don't think overwriting the original requirements of the webui with dreambooth requirements is wise. It might be an ok bandaid fix for now but what guarantees it won't break another feature of the automatik web-ui in the near future when automatik updates the requirements further and they're ignored while we're launching web-ui because we're pointing to dreambooth requirements instead of automatik requirements?
> 
> If this is an extension to automatik it should not be clashing with automatik's requirements.

I wouldn't really say this is clashing. Both the mechanism to use a different requirements file and torch command are part of the app for a reason.

For the requirements, we're only adding accelerate and bumping the diffusers version because otherwise, we can't load/save models properly.

For the torch version, this is needed because otherwise, the CUDA version clashes with 8-Bit Adam, which is necessary for most users under <12GB. 

I also discussed just bumping the Torch version with Automatic, and he pointed out that people *REALLY* have having to upgrade torch without a good reason. 

Unfortunately, dreambooth is a beast to run, so these optimizations are pretty necessary for most people.

**Comment by neojam** [comment]
I would say it's clashing, since the extension replaces the original contents of:
\venv\Lib\site-packages\diffusers\ 
with Version "0.8.0.dev0", removing the needed v0.3.0 version that AUTOMATIC1111 comes with.

I have 2 Problems with that:

- AUTOMATIC1111 GUI works completely offline once all requirements are downloaded. But the dreambooth extension breaks that offline functionality, since the extension wants to download v0.8.0 diffusers EVERY TIME you run the webui-user. If you're offline you'll get the "RuntimeError: Couldn't install requirements for Web UI." (even though 0.8.0 diffusers are already installed) and webui wont run. If you want the offline functionality back, you have to remove dreambooth extension and run webui.bat once, so it could download v0.3.0 diffusers (since dreambooth extension replaced those with v0.8.0). After that the webui will work offline again.

- The other problem: once I install the dreambooth extension I cant no longer generate images on my 3090Ti 24GB. Even when trying to generate 64x64 image I instantly get:
```
RuntimeError: CUDA error: out of memory
Time taken: 0.02s
Torch active/reserved: 2082/2284 MiB, Sys VRAM: 0/0 MiB (0.0%)
```

```
Error completing request
Arguments: ('diver in an ocean', '', 'None', 'None', 65, 0, False, False, 1, 3, 22, -1.0, -1.0, 0, 0, 0, False, 64, 64, True, 0.2, 0, 0, 0, False, False, False, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "x:\AI\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "x:\AI\stable-diffusion-webui\webui.py", line 51, in f
    shared.state.begin()
  File "x:\stable-diffusion-webui\modules\shared.py", line 187, in begin
    devices.torch_gc()
  File "x:\stable-diffusion-webui\modules\devices.py", line 36, in torch_gc
    torch.cuda.empty_cache()
  File "x:\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\memory.py", line 121, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: out of memory
```

No idea why its not working with 0.8.0 diffusers anymore....

**Comment by d8ahazard** [comment]
> I would say it's clashing, since the extension replaces the original contents of: \venv\Lib\site-packages\diffusers\ with Version "0.8.0", removing the needed v0.3.0 version that AUTOMATIC1111 comes with.
> 
> I have 2 Problems with that:
> 
> * AUTOMATIC1111 GUI works completely offline once all requirements are downloaded. But the dreambooth extension breaks that offline functionality, since the extension wants to download v0.8.0 diffusers EVERY TIME you run the webui-user. If you're offline you'll get the "RuntimeError: Couldn't install requirements for Web UI." (even though 0.8.0 diffusers are already installed) and webui wont run. If you want the offline functionality back, you have to remove dreambooth extension and run webui.bat once, so it could download v0.3.0 diffusers (since dreambooth extension replaced those with v0.8.0). After that the webui will work offline again.
> 
> Is it possible to make dreambooth extension to work offline? I've noticed the creation of a model that you want to train also needs access to internet and you cant create a model without it.
> 
> * The other problem: once I install the dreambooth extension I cant no longer generate images on my 3090Ti 24GB. Even when trying to generate 64x64 image I instantly get:
> 
> ```
> RuntimeError: CUDA error: out of memory
> Time taken: 0.02s
> Torch active/reserved: 2082/2284 MiB, Sys VRAM: 0/0 MiB (0.0%)
> ```
> 
> ```
> Error completing request
> Arguments: ('diver in an ocean', '', 'None', 'None', 65, 0, False, False, 1, 3, 22, -1.0, -1.0, 0, 0, 0, False, 64, 64, True, 0.2, 0, 0, 0, False, False, False, '', 1, '', 0, '', True, False, False) {}
> Traceback (most recent call last):
>   File "x:\AI\stable-diffusion-webui\modules\ui.py", line 185, in f
>     res = list(func(*args, **kwargs))
>   File "x:\AI\stable-diffusion-webui\webui.py", line 51, in f
>     shared.state.begin()
>   File "x:\stable-diffusion-webui\modules\shared.py", line 187, in begin
>     devices.torch_gc()
>   File "x:\stable-diffusion-webui\modules\devices.py", line 36, in torch_gc
>     torch.cuda.empty_cache()
>   File "x:\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\memory.py", line 121, in empty_cache
>     torch._C._cuda_emptyCache()
> RuntimeError: CUDA error: out of memory
> ```
> 
> No idea why its not working with 0.8.0 diffusers....

So, if you add the flags to the webui-user script as I posted above, it *should* work in offline mode, as we're just substituting variables already being used at launch. If it's not, then I need to take a look at the bit that tries to install the requirements, or just remove it and let people fend for themselves - which I suspect will just cause more issues than not....

**Comment by neojam** [comment]
All above was reported while running webui-user-dreambooth.bat that you posted.
It always tries to download the diffusers even though the requirement is already satisfied. The other instance where the extension doesn't work without internet connection is when you click on create model button. If you deny the connection, no model will be created. Maybe there is more, it was just were I stopped testing it, since the extension breaks webui for me completely (I always get out of memory error on prompting, so had to uninstall it for now).

You could test it with simple wall firewall:
https://github.com/henrypp/simplewall/releases
(great lightweight firewall for windows which shows pop-ups when something tries to connect to internet and you either can block it or allow it).

**Comment by ddxv** [comment]
Note for anyone else who ended up here after updating dreambooth and got the error:
```AttributeError: module 'dreambooth.conversion' has no attribute 'compile_checkpoint'```

For me the error did not show after restarting stable-diffusion-webui and I can see the dreambooth tab again.

**Comment by d8ahazard** [comment]
As this issue is related to something in requirements.txt that was already fixed, I'm closing this.
